-- MySQL Script generated by MySQL Workbench
-- Sat Jun 14 02:40:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema consumo_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema consumo_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `consumo_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `consumo_db` ;

-- -----------------------------------------------------
-- Table `consumo_db`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumo_db`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consumo_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumo_db`.`usuarios` (
  `idusuarios` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `data_cadastro` DATETIME NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consumo_db`.`consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumo_db`.`consumo` (
  `idconsumo` INT NOT NULL,
  `mes` VARCHAR(45) NOT NULL,
  `ano` VARCHAR(45) NOT NULL,
  `consumo_agua` DECIMAL(10,2) NOT NULL,
  `consumo_energia` DECIMAL(10,2) NOT NULL,
  `data_registro` DATETIME NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idconsumo`),
  INDEX `fk_consumo_usuarios_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_consumo_usuarios`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `consumo_db`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consumo_db`.`metas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumo_db`.`metas` (
  `idmetas` INT NOT NULL,
  `meta_agua` DECIMAL(10,2) NOT NULL,
  `meta_energia` DECIMAL(10,2) NOT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idmetas`),
  INDEX `fk_metas_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_metas_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `consumo_db`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
